version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/weather_dojo
      DB_USER: dojo_user
      DB_PASS: S3cret
      OPENWEATHERMAPAPPID: ${APP_ID}
    container_name: weather-dojo
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: weather_dojo
      POSTGRES_USER: dojo_user
      POSTGRES_PASSWORD: S3cret
    ports:
      - 5432:5432
    container_name: postgres14alpine
