server:
  port: 8080

spring:
  profiles:
    active: "prod"
  application:
    name: weather-dojo
  main:
    banner-mode: off

logging:
  level:
    root: INFO
  file:
    name: logs/weather-dojo.log