spring:
  jpa:
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
    open-in-view: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/weather_dojo}
    username: ${DB_USER:dojo_user}
    password: ${DB_PASS:S3cret}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never

openweathermap:
  appid: ${OPENWEATHERMAPAPPID:INSERT_SECRET_APP_ID_HERE}
  api:
    base-url: http://api.openweathermap.org/data/2.5